name: On Push to /file-to-read, Run

on:
  push:
    paths:
      - files-to-read/**
env:
  DEVOPS_DIR: devops


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8 #install the python needed
      - run: |
          python -m pip install --upgrade pip
          pip install pyats
      - name: execute py script # run file
        run: python3 action-text-2-mp3.py


# jobs:
#   hello-world:
#     name: Hello world
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check-out devops repository
#       uses: actions/checkout@v2
#       with:
#         repository: xanderstevenson/devops
# #         token: ${{ secrets.GITHUB_TOKEN }}
#         path: ${{ env.DEVOPS_DIR }}

#     - name: Hello World
#       run: python ${{ env.DEVOPS_DIR }}/hello_world.py
#       shell: sh


