name: On Push to /file-to-read, Run

on:
  push:
    # only runs when files in this path are changed
    paths:
      - files-to-read/**
env:
  DEVOPS_DIR: devops


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8 #install the python needed
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run file
        run: python3 action-text-2-mp3.py


      - name: Commit files # transfer the new files back into the repository
        run: |
          git config --local user.name "xanderstevenson"
          git add ./mp3s
          git commit -m "Updating the repository, mp3 in the ./mp3s folder"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: List of the GitHub Actions environment variables on Windows
        run: env

      - id: file_changes # see which file changed in the push
        uses: trilom/file-changes-action@v1.2.3
        with:
          outout: ''
          fileOutput: ''
      - name: test
        run:    |
         echo '${{ steps.file_changes.outputs.files_modified//[[\],.!]}}'

# jobs:
#   hello-world:
#     name: Hello world
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check-out devops repository
#       uses: actions/checkout@v2
#       with:
#         repository: xanderstevenson/devops
# #         token: ${{ secrets.GITHUB_TOKEN }}
#         path: ${{ env.DEVOPS_DIR }}

#     - name: Hello World
#       run: python ${{ env.DEVOPS_DIR }}/hello_world.py
#       shell: sh


